# Generated by Django 5.0.6 on 2024-10-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunteur',
            name='password',
            field=models.CharField(default=1234, max_length=128),
            preserve_default=False,
        ),
    ]
